### PR TITLE
Modify data tile server to static URL to fix CORS

### PR DESCRIPTION
**Pull request by vim-usds**

### CODE REVIEW

**Comment by vim-usds** [comment]
> That was fast! 🍏

When I realized it was set as an env, I thought.. "ohh a one-liner! I've heard about these fixes.. Let's just knock it out" 🤣

**Comment by vim-usds** [comment]
@jorge - this staging link is loading from the new static URL:

Screen Shot 2022-03-30 at 12 27 18 PM

Can you validate on your end?

**Comment by vim-usds** [comment]
@jorge - how does the GHA action look?

**Review by esfoobar-usds — APPROVED** [review]
🍏 looks good!

**Pull request merged**
