### PR TITLE
updating column E label to "Identified as disadvantaged"

### LINKED ISSUE #1398: Update column E label in download package csv/xlsx

### PR DESCRIPTION
**Pull request by katherinedm-usds**
fixes #1398

### CODE REVIEW

**Comment by esfoobar-usds** [comment]
Getting tests updated @katherinedm-usds

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by katherinedm-usds** [comment]
@esfoobar-usds when I download the .zip right now (~3 hours after merge) column E label is still the same - is there something else that has to happen for this update to make it into the https://d3jqyw10j8e7p9.cloudfront.net/data-pipeline/data/score/downloadable/Screening_Tool_Data.zip?

**Comment by esfoobar-usds** [comment]
Hi @katherinedm-usds. the download zip doesn't update until we run a score generation Github action, which I did this morning, so check it out now, it should be updated with your changes.

**Pull request merged**
