### PR TITLE
Add worst case scenario rollback plan

### PR DESCRIPTION
**Pull request by sverchdotgov**
Fixes: https://github.com/usds/justice40-tool/issues/947

This is ensuring we at least have some way to rollback in the worst case scenario of the data being corrupted somehow, and our upstream data sources being down in a way that prevents us from regenerating any datasets. See https://github.com/usds/justice40-tool/issues/946#issuecomment-989155252 for an analysis of the different ways the pipeline can fail and their impacts.

This guide is very brittle to pipeline changes, and should be considered a temporary solution for the worst case. I think that someday the github actions should run more frequently and write to different paths, perhaps with a timestamp. That would make rolling back more straightforward, as a previous version of the data would already exist at some path in s3.

### CODE REVIEW

**Comment by vim-usds** [comment]
@sverchdotgov - this is awesome!

I'm not sure about CLI access to AWS directly from our terminal. However I know that CLI access from GitHub actions work. See [here](https://github.com/usds/justice40-tool/blob/0d57dd572be027a2fc8b1625958ed68c4b900653/.github/workflows/deploy_staging.yml#L79).

I wonder if having these commands that you outlined could be placed into GitHub Action that can be triggered by the GitHub action UI, like [generate-census](https://github.com/usds/justice40-tool/blob/0d57dd572be027a2fc8b1625958ed68c4b900653/.github/workflows/generate-census.yml#L3) does. This may anyone to revert. 

Is this even possible, as some commands require python? Just my  $ .02!

**Review by switzersc-usds — APPROVED** [review]
🎉

**Review by vim-usds — APPROVED** [review]
LGTM!

**Comment by sverchdotgov** [comment]
Merging since we reviewed this. If we add rollbacks as github actions in the future this may become obsolete, but it works for now.

**Pull request merged**
