### PR TITLE
Refactor alerts

### PR DESCRIPTION
**Pull request by TomNUSDS**
* Remove J40Alert and classes
* Make AlertWrapper the primary component.
* Props to show one or both alerts
* Unit tests to verify one or both works correctly
* Update pages to use AlertWrapper
* Remove unused J40Aside.

Fixes: https://github.com/usds/justice40-tool/issues/554 and https://github.com/usds/justice40-tool/issues/541

### CODE REVIEW

**Comment by vim-usds** [comment]
Let's review this with design, it seems considerably different from existing designs, however I've also been knee deep on the docker side

**Comment by TomNUSDS** [comment]
@janelien @glennettec Can you look specifically at the alerts in this push and see what you think. 
They are slightly different from the mock-ups. 

This PR is a code refactor to combined two different alerts components.

https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/9bc150/en

**Comment by glennettec** [comment]
@TomNUSDS all elements on the page should be left aligned from the flag above the header to the footer. See attached images.
j40 screenshot - bottom
j40 screenshot - top

**Comment by vim-usds** [comment]
@glennettec and / or @jane

This PR is only really concerned with the Alert. In terms of the Alerts, does it look OK on each page? Specifically, how does the explore the tool page page look with the alert on top of the map?

https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/9bc150/en/cejst#3/32.47/-86.5

This is the currently on main:
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/cejst#3/32.47/-86.5

We see that Public beta alert was brought in for alignment. This seems to match the requested design. The Alert over the map was replaced with a standard Alert. Is that ok?

Screen Shot 2021-08-23 at 3 41 28 PM

**Comment by glennettec** [comment]
Got it! Looks good.

**Review by vim-usds — APPROVED** [review]
nice refactor!

**Pull request merged**
