### PR TITLE
Adding updated codebook to shapefile zip

### PR DESCRIPTION
**Pull request by emma-nechamkin**
This PR adds the csv column descriptions to the shapefile, while keeping original column names as well (in case we refactor and change the names). 

This is a little bit clumsy in that it takes place in etl score geo, but there isn't really a great place to put it right now.

### CODE REVIEW

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by katherinedm-usds** [comment]
Hi, I might not have been looking at the right links just now (I tried https://screeningtool.geoplatform.gov/en/methodology/?flags=stage_hash=1573/ab973fcabcf2cc909119ea4c7f7ecc67b88e0d6d and https://screeningtool.geoplatform.gov/en/methodology to download the shapefile) but columns.csv rows referencing internal names i.e. "Water Factor (Definition M)" are still there, so I'm not yet able to point shapefile users to a columns.csv that can use for their analysis. Can #1529 be updated with the link for QA'ing this? Thanks!

**Comment by emma-nechamkin** [comment]
You can see that when we have a column name specified in the yaml config (see the circled bit), it propagates for me.

**Comment by emma-nechamkin** [comment]
I restored the branch, but am wondering if this is an update thing? The staging link suggests the data has not been updated for download since 4/6.

**Comment by esfoobar-usds** [comment]
I guess the moral of this one -- let's be more explicit when we want product QA on a branch so that we (devs) don't merge before QA is completed.

**Comment by emma-nechamkin** [comment]
thank you both!!!

**Pull request merged**
