### PR TITLE
Issue 379 tox setup

### PR DESCRIPTION
**Pull request by widal001**
## Summary

Sets up `tox` for `data/data-roadmap/` and `data/data-pipeline/`

## Changes proposed

- Adds `tox` as a dev dependency to `data/data-pipeline/` via `poetry add` which modifies the following files:
  - `pyproject.toml`
  - `poetry.lock`
  - `requirements.txt` via `poetry export --dev --without-hashes > requirements.txt`
- Creates `tox.ini` files in `data-pipeline/` to run build tests in python versions 3.7, 3.8, and 3.9 
- Adds `.github/workflow/data-checks.yml` which execute the `tox` tests for both packages in `data` on pushes and pull requests

## Blockers or Questions

- [x] ~After migrating `data-roadmap` to `poetry` I was trying to run the unit tests in `utils_data_set_description_schema_test.py` using the `unittest` CLI but I either couldn't get it to recognize the unit tests or it would fail trying to load the tests. Below were all of the ways I tried running it, can you highlight what I might be doing wrong so we can check that the code still runs as expected after migrating it to `poetry`?~
  - ~`poetry run python -m unittest utils`~
  - ~`poetry run python -m unittest utils utils_data_set_description_schema_test.py`~
  - ~`poetry run python -m unittest discover utils -p "*_test.py"`~

## Instructions to review

- Make sure you have poetry installed on your local machine
- Checkout the PR locally
- Check `data/data-pipeline/`
  - Change directory into data-pipeline: `cd data/data-pipeline`
  - Install the package: `poetry install`
  - Run the the tests: `poetry run tox`, all tests should pass or be skipped (if you don't have that python version)
- ~~Check `data/data-roadmap/`~~
  - ~~Change directory into data-pipeline: `cd data/data-roadmap`~~
  - ~~Install the package: `poetry install`~~
  - ~~Run the the tests: `poetry run tox`, all tests should pass or be skipped (if you don't have that python version)~~

### CODE REVIEW

**Review by switzersc-usds — COMMENTED** [review]
Thanks for the PR! This looks good to me, and it runs fine locally. I'll defer to @esfoobar-usds or @lucasmbrown-usds though for a response to your question on using `poetry` with `unittest`.

**Comment by esfoobar-usds** [comment]
Spoke to @widal001 about this yesterday in Open Source Office Hours, and he will be doing a bit of refactoring to lint `data-pipeline` instead of `data-roadmap`

**Comment by widal001** [comment]
@esfoobar-usds I might actually just revert this PR to commit [2b0ddbe](https://github.com/usds/justice40-tool/pull/405/commits/2b0ddbea5843e5fcacfe6d478aeea0c3c0f6a911) so that it only modifies the `data/data-pipeline/` directory. That should make it clear for merging to `main` 

Then I'll branch from this to implement linting the `data/data-pipeline/` directory and address the flags I listed in #308 That should free this PR from becoming a bottleneck and allow us to start setting up unit testing with `tox` in parallel for the code in `data/data-pipeline/`

**Comment by widal001** [comment]
@esfoobar-usds @switzersc-usds Updated this PR so it only sets up `tox` for `data/data-pipeline/` All the automated checks now pass and you can follow the updated Review Instructions to test that it also works locally. If everything passes, it should be good to merge so we'll at least have the foundation of CI/CD set up for `data/data-pipeline`

**Review by esfoobar-usds — APPROVED** [review]
🍏 -- looks great!

**Pull request merged**
