### PR TITLE
Attempt no. 2 to fix auto-generated `main` link

### PR DESCRIPTION
**Pull request by NatHillardUSDS**
One more attempt to fix merging to main, it appears it doesn't like curly brackets

### CODE REVIEW

**Review by TomNUSDS — APPROVED** [review]
Yeah, this is the syntax I see more often.
(I did a search of github for similar code when I did the review the first time. I should have called out the `${{ }}` seemed non-standard. Sorry)

Approved!

**Comment by NatHillardUSDS** [comment]
Yeah, their [docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-expression-in-an-if-conditional) call out the below, indicating it should be working : 
```When you use expressions in an if conditional, you may omit the expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression, unless the expression contains any operators. If the expression contains any operators, the expression must be contained within ${{ }} to explicitly mark it for evaluation. For more information about if conditionals, see "Workflow syntax for GitHub Actions."```

but in practice it doesn't seem to, and real-world usage is low. Here's hoping this fixes this!

**Comment by switzersc-usds** [comment]
@NatHillardUSDS is this related to an existing issue we can connect it to?

**Comment by NatHillardUSDS** [comment]
Related to part of https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/125

**Pull request merged**
