### PR TITLE
Install and run pandas-vet

### PR DESCRIPTION
**Pull request by sverchdotgov**
This doesn't fix the errors, but it can give us a starting point for the discussion of which of these errors we care about.

See: https://github.com/usds/justice40-tool/issues/1115#issuecomment-1009206991

Part of: https://github.com/usds/justice40-tool/issues/1123

### CODE REVIEW

**Comment by sverchdotgov** [comment]
Current errors:

```
 $ flake8
./data_pipeline/tests/base/test_base.py:27:5: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/tests/base/test_base.py:123:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/tests/base/test_base.py:124:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/tests/base/test_base.py:139:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/tests/base/test_base.py:140:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/tests/base/test_base.py:155:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/tests/base/test_base.py:156:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/base.py:138:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/michigan_ejscreen/etl.py:47:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/calenviroscreen/etl.py:53:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census/etl_utils.py:74:5: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/hud_housing/etl.py:52:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/national_risk_index/etl.py:96:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_acs_2010/etl.py:122:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/census_acs_median_income/etl.py:97:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_acs_median_income/etl.py:149:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_acs_median_income/etl.py:186:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_acs_median_income/etl.py:209:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/hud_recap/etl.py:41:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/hud_recap/etl.py:60:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/mapping_inequality/etl.py:71:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/mapping_inequality/etl.py:78:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/mapping_inequality/etl.py:166:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_decennial/etl.py:273:17: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/census_decennial/etl.py:275:17: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/census_decennial/etl.py:300:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_decennial/etl.py:301:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_decennial/etl.py:379:35: PD003 '.isna' is preferred to '.isnull'; functionality is equivalent
./data_pipeline/etl/sources/geocorr/etl.py:54:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/tree_equity_score/etl.py:99:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/ejscreen/etl.py:63:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/census_acs/etl.py:224:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/census_acs/etl.py:227:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/census_acs/etl_utils.py:57:5: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/persistent_poverty/etl.py:45:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/sources/persistent_poverty/etl.py:110:13: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/cdc_places/etl.py:39:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/cdc_places/etl.py:46:19: PD010 '.pivot_table' is preferred to '.pivot' or '.unstack'; provides same functionality
./data_pipeline/etl/sources/cdc_places/etl.py:53:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/sources/housing_and_transportation/etl.py:54:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/score/etl_score_post.py:57:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/score/etl_score_post.py:136:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/score/etl_score_post.py:187:13: PD003 '.isna' is preferred to '.isnull'; functionality is equivalent
./data_pipeline/etl/score/etl_utils.py:90:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/score/etl_utils.py:103:9: PD003 '.isna' is preferred to '.isnull'; functionality is equivalent
./data_pipeline/etl/score/etl_score_geo.py:86:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/score/etl_score_geo.py:114:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/score/etl_score_geo.py:166:9: PD002 'inplace = True' should be avoided; it has inconsistent behavior
./data_pipeline/etl/score/etl_score.py:193:17: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/score/etl_score.py:367:13: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/etl/score/etl_score.py:382:9: PD901 'df' is a bad variable name. Be kinder to your future self.
./data_pipeline/score/score_l.py:57:14: PD003 '.isna' is preferred to '.isnull'; functionality is equivalent
./data_pipeline/score/score_l.py:57:14: PD003 '.isna' is preferred to '.isnull'; functionality is equivalent
./data_pipeline/score/score_l.py:86:15: PD004 '.notna' is preferred to '.notnull'; functionality is equivalent
./data_pipeline/score/score_l.py:674:15: PD004 '.notna' is preferred to '.notnull'; functionality is equivalent
```

@saran-ahluwalia Do we want to ignore any of these?

**Comment by saran-ahluwalia** [comment]
@sverchdotgov I personally think `PD003` is harmless - as the functionality is equivalent for both method calls.

**Comment by saran-ahluwalia** [comment]
@sverchdotgov Apologies - I should have added _why_ the above are method calls are innocuous. It's literally in the source [code](https://github.com/pandas-dev/pandas/blob/0409521665bd436a10aea7e06336066bf07ff057/pandas/core/dtypes/missing.py#L109).

**Comment by saran-ahluwalia** [comment]
The `inplace` warnings are very legitimate concerns. This SF [post](https://stackoverflow.com/a/60020384) details why.

**Comment by lucasmbrown-usds** [comment]
@saran-ahluwalia , do you want to work on finalizing the rules and fixing the errors above? Thanks!

**Comment by sverchdotgov** [comment]
@saran-ahluwalia Here's the issue: https://github.com/usds/justice40-tool/issues/1123

If branching off the PR is easier that works, although I noticed it has merge conflicts now.

**Comment by saran-ahluwalia** [comment]
Thanks for this addition. The associated tasks outlined [here](https://github.com/usds/justice40-tool/issues/1115#issue-1098170100) are excellent. Is there any issue capturing addressing `inplace = True` flags?

**Comment by sverchdotgov** [comment]
@saran-ahluwalia Yup, https://github.com/usds/justice40-tool/issues/1123 is the issue that tracks fixing all the linter issues.

I'll update the description to include your comments above.

**Comment by esfoobar-usds** [comment]
Where is this showing at the moment? Does it popup on VSCode errors? Or on `code-checks`? I would not merge this PR if this is introducing noise or preventing us to work for now with these warnings

**Comment by saran-ahluwalia** [comment]
@sverchdotgov - I am working on #1123 and branched off your topic branch. I have done the following:

1. `poetry install`
2. From the directory `justice40-tool/data/data-pipeline` executed `flake 8 .` as shown above

Result:

Screen Shot 2022-01-13 at 7 57 16 AM

I was wondering if these steps are correct. I am using Python 3.9 and the most current version of Poetry.

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Pull request merged**
