### PR TITLE
New side panel with Exceed thresholds, up/down arrows and background highlighting

### LINKED ISSUE #1086: Missing data - replace N/A with --
**Describe the bug**
Go somewhere where data is missing (like one of the territories). View the solution to use N/A... it looks weird. because it is applicable (it is just missing). Suggest replacing with double dashes (--) when data is not available for the indicator.

**To Reproduce**
1. Go to 'a territory on the explore the tool page'
2. Click on 'a census track'
3. Scroll down to 'category > data indicator'
4. Note the use of NA when data is missing / not available

**Expected behavior**
Replace N/A with dashes (--) when data is not available

**Screenshots**
Screen Shot 2021-12-27 at 10 53 42 AM

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #1239: Implement Backend Staging Hash on Frontend
We need to be able to communicate to the frontend app via the URL to pull from a different S3 endpoint, which would be the variable staging folder generated on a backend PR.

@vim-usds to coordinate with @esfoobar-usds

### LINKED ISSUE #1311: Implement the side panel to make the formula more apparent
# Purpose
Update sidepanel to match mock:
Screen Shot 2022-02-22 at 1 13 44 PM

## Task list ExceedBurden and AND components
- [x] create new component for Exceed text
- [x] add AND spacer, push into container
- [x] have burdens push into parent container
- [x] determine which fields will be coming from the BE
- [x] create BE ticket for Emma
- [x] intl on EXCEED and AND component
- [x] hook up BE signal stubs
- [x] create/ runs tests for EXCEED and AND tests

## Tasks for new IndicatorValue component
- [ ] create a new InidicatorValue component
- [ ] hook up BE stubs
- [ ] intl
- [ ] tests

## Tasks for general testing
- [ ] ensure mobile / tablet friendly

### Should the BE send answers to burden questions?
 Should BE send the boolean value to the following two questions:
Screen Shot 2022-02-22 at 7 16 24 PM
Screen Shot 2022-02-22 at 7 16 36 PM

I can deduce Y/N values (as the BE already sends the booleans for each category so simply adding them up would allow me to figure it out), however, there's a part of me that feels that to be consistent with our architecture of all data coming from the backend, we may want to add two more booleans as the answer to each question? Thinking about this more, errors on the booleans may propagate if the FE figures it out

### Should the BE send the threshold value and direction?
Screen Shot 2022-02-22 at 7 20 52 PM

Assumptions
1. the value sub-text's direction will be (for the near future) `above` or `below` only
2. the threshold will always be a 2 digit number followed by `th` of `%` 

Can the BE send this information on a per tile basis? This would allow us to change thresholds. Also it's OK if it's not sent as this is more of a score/methodology thing which, if it changes, will effect other parts of the site as well, ie, the methodology page.

### PR DESCRIPTION
**Pull request by vim-usds**
# Purpose
This PR will
- closes #1311 
- adds 2 _Exceeds burdens_ and a AND section to side panel
- make indicator background highlight when the indicator is above (or below) a threshold 
- adds up/down and unavailable icons to each indicator
- remove Indicators header
- update the low income threshold
- closes #1239  
- will allow the use of a data-pipeline staging url as a feature flag (`?flags=stage_hash=PR_NUMBER/HASH`)in any client side URL (local, staging or prod)
- closes #1086 

## QA feedback round 1
- [x] Make the Yes / No bold
- [x] N/A values should show no up/down arrow or above/below threshold
- [x] N/A subtext should read data is unavailable
- [x] message to Emma on boolean errors
- [x] low income should be above 65% (disadvantaged)
- [x] integrate new BE signals with staging URL

## QA feedback round 2
- [x] new not available icon 🚫  seems good
- [x] fix bug where indicators with a value of zero show the 🚫  icon

## QA feedback round 3
- ?

### CODE REVIEW

**Comment by vim-usds** [comment]
Let's add a 1 px space between indicators to allow for a white line. Let's also bold the font.

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by vim-usds** [comment]
Feedback

1. Make the Yes / No bold
2. See bugs in Side Panel Testing doc

**Comment by vim-usds** [comment]
@emma-nechamkin,

Some QA feedback led to boolean strangeness. Was able to spin up Jupyter (which is my new favorite tool) to investigate:

Screen Shot 2022-03-08 at 6 19 13 PM

Any thoughts? Wondering if I'm doing something wrong (likely). Thanks!

**Comment by emma-nechamkin** [comment]
@vim-usds these booleans are for "low income, low ed, and exceeds 90th percentile" -- we don't pipe the threshold booleans to you separately, I don't think. 

I *think* for the new side panel, we might need to pass this through!

```field_names.ENERGY_BURDEN_LOW_INCOME_LOW_HIGHER_ED_FIELD: "EBLI",```

**Pull request closed without merging**
