### PR TITLE
Rezip CSV and Excel with Codebook

### LINKED ISSUE #1679: Rezip in the .csv and .xls files and include the codebook with each
**Describe the bug**
Trying to solve a problem I created, can we include the codebook with the .csv and .xls files and have them as zip files? this solves two problems - one, it let's people get access to the codebook which they may need to understand the column names and two, it solves for the .csv on safari which just opens in another tab making it less useful for analysis purposes. Unfortunately I think this is both a front and back-end update.

**To Reproduce**
1. Go to 'Methodology & data'
2. Click on 'Downloads.'
3. Scroll down to 'the two file downloads.'

**Expected behavior**
See above. Will need to update to say it is a .zip containing a .xls (or .csv) and a codebook and the unzipped file size.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by esfoobar-usds**
Fixes #1679 

This PR adds a version string that can be overwridden from an environment variable `J40_VERSION_LABEL_STRING` and also can override the date string with the environment variable `J40_VERSION_DATE_STRING`

### CODE REVIEW

**Review by vim-usds — COMMENTED** [review]
Hey @esfoobar-usds , is this going to main or the BE release branch?

If it's going to main, I think it's fine to combine FE and BE stuff, if not, I might vote for keeping it BE separate from FE

**Comment by esfoobar-usds** [comment]
It's going against `main` @vim-usds

**Review by vim-usds — APPROVED** [review]
LGTM!

**Comment by vim-usds** [comment]
@esfoobar-usds , can you include this fix in this merge to main?

https://github.com/usds/justice40-tool/pull/1936/files

**Comment by esfoobar-usds** [comment]
@vim-usds added!

**Pull request merged**
