### PR TITLE
Make side panel formula more apparent

### LINKED ISSUE #1086: Missing data - replace N/A with --
**Describe the bug**
Go somewhere where data is missing (like one of the territories). View the solution to use N/A... it looks weird. because it is applicable (it is just missing). Suggest replacing with double dashes (--) when data is not available for the indicator.

**To Reproduce**
1. Go to 'a territory on the explore the tool page'
2. Click on 'a census track'
3. Scroll down to 'category > data indicator'
4. Note the use of NA when data is missing / not available

**Expected behavior**
Replace N/A with dashes (--) when data is not available

**Screenshots**
Screen Shot 2021-12-27 at 10 53 42 AM

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #1239: Implement Backend Staging Hash on Frontend
We need to be able to communicate to the frontend app via the URL to pull from a different S3 endpoint, which would be the variable staging folder generated on a backend PR.

@vim-usds to coordinate with @esfoobar-usds

### LINKED ISSUE #1311: Implement the side panel to make the formula more apparent
# Purpose
Update sidepanel to match mock:
Screen Shot 2022-02-22 at 1 13 44 PM

## Task list ExceedBurden and AND components
- [x] create new component for Exceed text
- [x] add AND spacer, push into container
- [x] have burdens push into parent container
- [x] determine which fields will be coming from the BE
- [x] create BE ticket for Emma
- [x] intl on EXCEED and AND component
- [x] hook up BE signal stubs
- [x] create/ runs tests for EXCEED and AND tests

## Tasks for new IndicatorValue component
- [ ] create a new InidicatorValue component
- [ ] hook up BE stubs
- [ ] intl
- [ ] tests

## Tasks for general testing
- [ ] ensure mobile / tablet friendly

### Should the BE send answers to burden questions?
 Should BE send the boolean value to the following two questions:
Screen Shot 2022-02-22 at 7 16 24 PM
Screen Shot 2022-02-22 at 7 16 36 PM

I can deduce Y/N values (as the BE already sends the booleans for each category so simply adding them up would allow me to figure it out), however, there's a part of me that feels that to be consistent with our architecture of all data coming from the backend, we may want to add two more booleans as the answer to each question? Thinking about this more, errors on the booleans may propagate if the FE figures it out

### Should the BE send the threshold value and direction?
Screen Shot 2022-02-22 at 7 20 52 PM

Assumptions
1. the value sub-text's direction will be (for the near future) `above` or `below` only
2. the threshold will always be a 2 digit number followed by `th` of `%` 

Can the BE send this information on a per tile basis? This would allow us to change thresholds. Also it's OK if it's not sent as this is more of a score/methodology thing which, if it changes, will effect other parts of the site as well, ie, the methodology page.

### PR DESCRIPTION
**Pull request by vim-usds**
## Tickets this PR closes
- closes #1311 
- closes #1239  
- closes #1086 

###  Make side panel formula more apparent <a href="#sp-more-app" id="sp-more-app">#</a>
QA this feature [here](http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/1463-db7d85/en/cejst/?flags=stage_hash=1393/596b31759c7dd72460a61ae109601fc7d6d4ac9c#9.03/33.2649/-116.35)

#### QA tester
- [x] Kameron
- [ ] Katherine
- [ ] Beth
- [ ] Jorge
- [ ] Vim
- [ ] Emma
- [ ] Lucas

#### QA spec 

- [x] EXCEED burden spacer is in 
- [x] AND burden spacer is in
- [x] if indicator is exceeded the background color should not be white
- [x] adds up/down and unavailable icons to each indicator
- [x] remove Indicators header
- [x] Make the Yes / No bold
- [x] N/A values should show no up/down arrow or above/below threshold
- [x] N/A subtext should read data is unavailable
- [x] low income should be above 65% (disadvantaged)
- [ ] new not available icon 🚫  is good
- [ ] indicators with a value of zero does NOT show the 🚫  icon

### CODE REVIEW

**Comment by KameronKerger** [comment]
something weird is happening @vim-usds. low income and higher ed seem to be missing from the IF statement
Screen Shot 2022-03-21 at 8 18 12 AM
?

**Comment by vim-usds** [comment]
> something weird is happening @vim-usds. low income and higher ed seem to be missing from the IF statement Screen Shot 2022-03-21 at 8 18 12 AM ?

Hey @KameronKerger - When I run it seems to work, I'm wondering if we need to clear the cache? If that doesn't fix it, we may want to investigate as it might be happening to others as well. 

Screen Shot 2022-03-21 at 8 32 42 AM

@katherinedm-usds - 
Also if this fixes it, it brings up an important point of possibly fixing the user's cache as this could be happening to others:
https://github.com/usds/justice40-tool/issues/1156

**Comment by KameronKerger** [comment]
Screen Shot 2022-03-23 at 2 10 07 PM
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/1463-db7d85/en/cejst/?flags=stage_hash=1393/596b31759c7dd72460a61ae109601fc7d6d4ac9c#12.82/15.2109/145.76579

**Comment by KameronKerger** [comment]
Screen Shot 2022-03-23 at 2 12 05 PM
should be above 65th percentile

**Comment by KameronKerger** [comment]
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/1463-db7d85/en/cejst/?flags=stage_hash=1393/596b31759c7dd72460a61ae109601fc7d6d4ac9c#9.65/33.2901/-114.4202

**Comment by KameronKerger** [comment]
Screen Shot 2022-03-23 at 2 19 52 PM

**Pull request closed without merging**
