### PR TITLE
Updating EJScreen data

### PR DESCRIPTION
**Pull request by emma-nechamkin**

### CODE REVIEW

**Comment by vim-usds** [comment]
@emma-nechamkin - this seem to have a number of other commits in this PR. Is that purposeful?

**Comment by vim-usds** [comment]
Also, it seem that the back end staging script is failing on the last run, should we make sure that passes?

**Comment by emma-nechamkin** [comment]
> @emma-nechamkin - this seem to have a number of other commits in this PR. Is that purposeful?

no definitely not! also these files did not match what I have locally o.O. Updates pending

**Comment by emma-nechamkin** [comment]
@vim-usds i created a new base instead of rebasing this :/

**Pull request closed without merging**
