### PR TITLE
Change Explore the tool to Explore the map

### PR DESCRIPTION
**Pull request by vim-usds**
# Purpose
Change the website to say `Explore the map` from `Explore the tool`. This change occurs in 5 places (see QA spec).

This change is fairly large and will impact the translations we have in the queue. Since we encode the page title in the IDs, for example, `explore.tool.page.heading.1`. These were all updated to `explore.map.page.heading1`. When the spanish translation comes in, doing a global find and replace of `tool` with `map`, should (🤞 ) work. 

Note the Alert banner is set to expire on April 25th - this is set here. Anyone can change this date. 

## QA testing round 1
It would be great if the QA person could check off the QA specs below communicating that they are complete and ready to be merged.

### QA spec:
- [x] Change "Explore the tool" to "Explore the map" in top nav
- [x] Change alert "Improvements to the map on the Explore the tool page" to "Improvements to the Explore the map page" (consulted with @KameronKerger) 
- [x] Change "Explore the tool" to "Explore the map" in https://screeningtool.geoplatform.gov heading 
- [x] Change "Explore the tool" link to "Explore the map" on [About](https://screeningtool.geoplatform.gov/en/about)
- [x] Change "Explore the tool" link on [Contact](https://screeningtool.geoplatform.gov/en/contact) under "Census tract feedback"
- [x] I've done a CTRL+F (find) on each page for the term `tool`. Everywhere that the term `tool` still exists, it is meant to say `tool`. 

PS - Really appreciating the Acceptance Criteria of ticket [1546](https://github.com/usds/justice40-tool/issues/1546) as this made creating the QA spec super easy!

## QA testing round 2
This ticket was started prior to my retreat and had over 25 files in conflict with a number being in the Spanish side.

### QA spec:
- [ ] Validated that all QA specs from round1 are still functional
- [ ] Validated that all Spanish content is translated 
- [ ] Reviewed site for any other potential changes from what is currently on main

### CODE REVIEW

**Comment by KameronKerger** [comment]
no QA link @vim-usds

**Comment by KameronKerger** [comment]
@vim-usds looking good. if we could get the 
Improvements to the **map** on the Explore the map page
changed to
Improvements to the **tool** on the Explore the map page
Screen Shot 2022-04-12 at 3 08 10 PM

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by katherinedm-usds** [comment]
I looked at the QA link and I think these look good

- [ ] Change "Explore the tool" to "Explore the map" in top nav
image

- [ ]  Change "Explore the tool" to "Explore the map" in https://screeningtool.geoplatform.gov/ heading

image

- [ ]  Change "Explore the tool" link to "Explore the map" on [About](https://screeningtool.geoplatform.gov/en/about)

image
image



- [ ] Change "Explore the tool" link on [Contact](https://screeningtool.geoplatform.gov/en/contact) under "Census tract feedback"
image


However, I don't think this change is needed or should be done because the information is provided by CEJST, i.e. the tool, in both the map, and the data downloads
image

 - [ ] I've done a CTRL+F (find) on each page for the term tool. Everywhere that the term tool still exists, it is meant to say tool.


I don't think this alert still applies
- [ ]  Change alert "Improvements to the map on the Explore the tool page" to "Improvements to the Explore the map page" (consulted with @KameronKerger)

**Comment by vim-usds** [comment]
@KameronKerger - do you have thoughts on the side panel changes from map to tool?

**Comment by vim-usds** [comment]
@katherinedm-usds - thanks for the awesome review!

**Comment by KameronKerger** [comment]
@vim-usds and @katherinedm-usds I think it needs to still be tool because the map isn't doing all of those things...

**Comment by vim-usds** [comment]
> @vim-usds and @katherinedm-usds I think it needs to still be tool because the map isn't doing all of those things...

@KameronKerger - thank you. Just to validate, should we change all 3 instance of `map` in the sidepanel to `tool`? E.g., 

1. This `map` identifies communities that are marginalized, underserved, ...
2. The `map` uses census tracts that represent about 4,000 people, which ...
3. The `map` ranks each census tract using percentiles ...

All 3 of the above instances of `map` should be `tool`?

**Comment by KameronKerger** [comment]
answering here for the record. yes @vim-usds.

**Pull request merged**
