### PR TITLE
Analysis by region

### PR DESCRIPTION
**Pull request by lucasmbrown-usds**
This PR accomplishes a few things: 
* Adds a regional breakdown to the comparison tool 
* Fixes a couple small ETL issues that popped up while I was running `main` 
* Adds a "secondary comparison" tool: 
```
The first level of comparison identifies census tracts prioritized by Method A,
    compared to whether or not they're prioritized by Method B.

    This comparison method analyzes characteristics of those census tracts, based on whether or not they are prioritized
    or not by Method A and/or Method B.


    E.g., it might show that tracts prioritized by A but not B have a higher average income,
    or that tracts prioritized by B but not A have a lower percent of unemployed people.
```

Open question for @esfoobar-usds: right now our comparison tool outputs are in a folder inside `tmp`, but should we follow the pattern of the `datasets` directory and make them their own directory, so they don't get cleared out each time we wipe `tmp`?

### CODE REVIEW

**Review by esfoobar-usds — DISMISSED** [review]
🍏 -- but there's some conflicts, so please pull `main` and rebase or merge and fix the conflicts

**Comment by lucasmbrown-usds** [comment]
Oh and @esfoobar-usds -- just flagging this from the PR description for you: 

> Open question for @esfoobar-usds: right now our comparison tool outputs are in a folder inside `tmp`, but should we follow the pattern of the datasets directory and make them their own directory, so they don't get cleared out each time we wipe tmp?

**Comment by esfoobar-usds** [comment]
@lucasmbrown-usds Totally!

**Comment by switzersc-usds** [comment]
> should we follow the pattern of the datasets directory and make them their own directory, so they don't get cleared out each time we wipe tmp?
yes please!

**Comment by switzersc-usds** [comment]
Running this locally, I get the following error in [9]:
```
 ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Score D (top 30th percentile)'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-9-ea0c68fc7bd0> in <module>
    210 )
    211 
--> 212 state_distribution_df = get_state_distributions(
    213     df=merged_with_state_information_df,
    214     priority_communities_fields=fields_to_analyze,

<ipython-input-9-ea0c68fc7bd0> in get_state_distributions(df, priority_communities_fields)
      6     # Ensure each field is boolean.
      7     for priority_communities_field in priority_communities_fields:
----> 8         if df[priority_communities_field].dtype != bool:
      9             print(f"Converting {priority_communities_field} to boolean.")
     10 

/usr/local/lib/python3.9/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'Score D (top 30th percentile)'
```

**Review by switzersc-usds — APPROVED** [review]
Runs and looks good to me! Once this is merged I'll update the docs PR I just made.

**Pull request merged**
