### PR TITLE
Changing LHE in tiles to a boolean

### PR DESCRIPTION
**Pull request by emma-nechamkin**

### CODE REVIEW

**Comment by emma-nechamkin** [comment]
@vim-usds  here LHE and IALHE is changed from a float to a bool. Does anything on the front end have to change?

**Comment by vim-usds** [comment]
> @vim-usds here LHE and IALHE is changed from a float to a bool. Does anything on the front end have to change?

@emma-nechamkin - Yes there is! Thanks for brining this up!

Basically this :

```
    if (indicatorName === 'highSchool') {
      return properties.hasOwnProperty(constants
          .IS_LOW_HS_EDUCATION_LOW_HIGHER_ED_PRIORITIZED) &&
        properties[constants.IS_LOW_HS_EDUCATION_LOW_HIGHER_ED_PRIORITIZED] == 1 ?
        true : false;
    }
 ```
 
 Needs to change to this:
 ```
     if (indicatorName === 'highSchool') {
      return properties.hasOwnProperty(constants
          .IS_LOW_HS_EDUCATION_LOW_HIGHER_ED_PRIORITIZED) ?
        properties[constants.IS_LOW_HS_EDUCATION_LOW_HIGHER_ED_PRIORITIZED] : null;
    }
```

Should I create a ticket for this?

**Comment by emma-nechamkin** [comment]
I think so! I'm also happy to change it on this ticket if that's not HORRIBLE practice, if you tell me what the filename is?

**Review by vim-usds — APPROVED** [review]
LGTM

**Comment by vim-usds** [comment]
Steps left on this:

- [ ] Wait for staging link 
- [ ] Verify float to bool on an associated front-end PR and post here
- [ ] Merge this PR!

**Comment by vim-usds** [comment]
@emma-nechamkin - a quick check on the frontend, is showing that these booleans are coming in nicely! Nice work! 🚀 

Also it seems that maybe you are adding the "leaky underground" stuff into this branch. What is the scope of this PR that you're thinking? 

Assuming it will only be the leaky stuff, then I could wait until that is completed (and we can agree on some new backend signal names for those indicators), I get a new staging URL, test with the frontend, and then we can merge?

I'm open to anything!

**Comment by emma-nechamkin** [comment]
@vim-usds such a great question! So I think each new indicator we add will have a new backend ticket. Maybe it makes sense to wait for ALL of that to be completed? wdyt?

**Comment by emma-nechamkin** [comment]
This sounds perfect to me, @vim-usds, and is aligned with how I was thinking of doing it on the backend. 

Then, at the "end" of the process, we would merge into a single release branch? Or keep separate the FE and BE?

**Comment by vim-usds** [comment]
> This sounds perfect to me, @vim-usds, and is aligned with how I was thinking of doing it on the backend.
> 
> Then, at the "end" of the process, we would merge into a single release branch? Or keep separate the FE and BE?

Great question! Apart of me is thinking we still keep a separate BE release branch and FE release branch.

We will soon ( maybe a few days) have a  "staging 1.0 link" or "staging narwhal link". This "staging 1.0 link" will be a FE staging link (which will be generated by the open PR from the FE release branch => main) pointing to some BE staging link (which will be generated by the open PR from the BE release branch => main). Kinda the usual thing. 

Once all FE features for 1.0 are approved by QA on the "staging 1.0 link", we can merge the BE release branch into main. Then will want to push all the BE code to production (I think we have to run some GHA to push to AWS). Very shortly after we can merge the FE release branch into main and hopefully that will mark the completion of the 1.0 release!

Let me know if that all sounds good to you!

@jorge - please review and raise any red flags if you see them! TY!

**Comment by emma-nechamkin** [comment]
@vim-usds this sounds good to me. lmk when i'm good to merge this!

**Comment by vim-usds** [comment]
@emma-nechamkin - yes! As soon as this is merged and closed, I will merge the associated FE ticket to the FE release branch :)

**Pull request merged**
