### PR TITLE
Fixed es.json

### PR DESCRIPTION
**Pull request by TomNUSDS**
- converted remaining english to spanish in file so as to check more html locations.
- the `formatjs compile` for Spanish was failing converted back to english for now. build does the correct thing, so it's more just to keep things correct in source.

### CODE REVIEW

**Review by nathillard — DISMISSED** [review]
Hm, this works for now; I would think it may make sense to leave this file blank for now? We risk misrepresenting things with our google translate version. 

I would also see if you could add this actually? https://formatjs.io/docs/tooling/linter/ - this way we catch missing translations with our linter itself.

**Comment by TomNUSDS** [comment]
> Hm, this works for now; I would think it may make sense to leave this file blank for now? We risk misrepresenting things with our google translate version.

Yeah, hopefully we wouldn't hand them our es.json but just feed the en.json into the translation tool. 

It's likely all text on the site will be replaced in the next batch of UI changes, so I'll just empty the es.json with those.

Random thought: maybe we should have some mock language code for Ipsum Lorem? Would be fun to have some iplo.json in the language file that jest could sanity check going to /iplo/ replaces all the text correctly.

> I would also see if you could add this actually? https://formatjs.io/docs/tooling/linter/ - this way we catch missing translations with our linter itself.

Good thinking. I'll check into it.

**Comment by TomNUSDS** [comment]
Added `eslint-plugin-formatjs` checking. Think typescript does most of the enforcing we need, but nice to have anyways.

**Review by nathillard — APPROVED** [review]
LGTM - we should make sure to not go live with the Google translate versions

**Review by NatHillardUSDS — APPROVED** [review]
Approving with correct account this time

**Pull request merged**
