### PR TITLE
Add ETL Contract Checks

### LINKED ISSUE #617: As a code maintainer, I want to be able to validate that the output of each source ETL class adheres to a standard contract, so that no additional transformation is needed to compare or utilize those outputs in the scoring module.
## Description
Currently there are several inconsistencies across the outputs of ETL classes in `etl/sources/`. For example: 
- Some outputs are written as a GeoJSON instead of as a csv file
- Some outputs are saved at the Census Tract level instead of at the Census Block Group Level
- Some outputs contain the Census Block Group FIPS code, but the column with that information is named something else
- Some outputs contain indicator columns that need to be renamed before they are used in the score

Because of these inconsistencies, the `ScoreETL` class needs to do a fair amount of standardization across these sources before it can combine and uses them in the score. As a result, we need a mechanism for testing and enforcing that source ETL classes produce outputs that adhere to a standard ETL contract.

## Solution
Create a series of methods on the `ExtractTransformLoad` base class that can be called by the source ETL classes that inherit from it which will help those classes standardize their ETL output and validate that the output adheres to the ETL contract.

## Tasks

- [ ] Create a series of class globals and attributes on `ExtractTransformLoad` class that can be used by each source ETL class and can be checked for compliance against the contract
  - [ ] `CENSUS_CSV` (class global) Used to read in the definitive list of Census Block Group FIPS codes from the census data
  - [ ] `self.NAME` (class attribute) Used to create output path and populate logger info
  - [ ] `self.SOURCE_URL` (class attribute) Used to extract source data in `self.extract()`
  - [ ] `self.OUTPUT_PATH` (class attribute) Location where output csv is written in `self.load()`
  - [ ] `self.SCORE_COLS` (class attribute) List of columns that will be used in the score and should appear in the output csv
  - [ ] `self.FIPS_CODES` (class attribute) Dataframe of Census Block Group FIPS codes used to standardize the columns in the output csv
- [ ] Create a private method `self._get_census_fips_codes()` which extracts the Census Block Group and Census Tract FIPS codes from the Census data and stores it in `self.FIPS_CODES`
- [ ] Create an `ExtractTransformLoad.validate_output()` method that can be optionally called to check the compliance of the output of ETL classes with the conditions below:
  - [ ] An output csv has been created in the `data/dataset/{data_source_name}` directory
  - [ ] The output csv has a column named `GEOID10` which stores the census block group FIPS code
  - [ ] The columns in the output csv include the fields that will be used in the score and the names of those columns match the value expected by the score.
  - [ ] The `GEOID10` column contains all of the Census block groups
- [ ] Update `NationalRiskIndexETL` to conform to the new contract enforced by `ExtractTransformLoad.validate_output()`

## Definition of "Done"

- [ ] ETL classes that inherit from the `ExtractTransformLoad` class can check that their output adheres to the ETL contract by running `super().validate_output()` 
- [ ] Running `NationalRiskIndexETL.validate_output()` will result in a passing check

### PR DESCRIPTION
**Pull request by widal001**
## Summary

Creates a series of methods on the `ExtractTransformLoad` base class that simplify and validate adherence to a standardized ETL contract for dataset sources. Fixes #617 

## Changes Proposed

- Changes to `data_pipeline/etl/base.py`
  - Adds class GLOBAL `CENSUS_CSV` that can be used to read in the definitive list of Census Block Group FIPS codes from the census data
  - Creates an `__init__()` method to instantiate class attributes that can be used by each source ETL class and can be checked for compliance against the contract
    -  `self.NAME` Used to create output path and populate logger info
    -  `self.SOURCE_URL` Used to extract source data in self.extract()
    -  `self.OUTPUT_PATH` Location where output csv is written in self.load()
    -  `self.SCORE_COLS` List of columns that will be used in the score and should appear in the output csv
    -  `self.FIPS_CODES` Dataframe of Census Block Group FIPS codes used to standardize the columns in the output csv
  - Create a private method `self._get_census_fips_codes()` which extracts the Census Block Group and Census Tract FIPS codes from the Census data and stores it in `self.FIPS_CODES`
  - Implements `self._get_yaml_config()` which parses a yaml file for the class and uses it to set class attributes in `__init__()`
  - Create an `self.validate_output()` method that can be optionally called to check the compliance of the output of ETL classes with the conditions below:
    - An output csv has been created in the `data/dataset/{data_source_name}` directory
    - The output csv has a column named `GEOID10` which stores the census block group FIPS code
    - The columns in the output csv include the fields that will be used in the score and the names of those columns match the value expected by the score.
    - The `GEOID10` column contains all of the Census block groups
- Creates `tests/base/` directory to test the new methods added to `etl/base.py`

## Blockers or Questions

- [x] Several of these methods need to distinguish between the census ETL and the other dataset ETL classes, currently I've implemented this check by adding a key `is_dataset` to the `config.yaml` file. Is there a more elegant way to implement this check across class methods?
- [x] Are there other configuration variables we want to add to the `config.yaml` file for each dataset ETL? Or other class attributes that should be shared across dataset ETL classes?

## Additional Context 

A few of the features implemented in this PR are also designed to simplify the process of creating a "wizard" for new ETL classes, as described in #576, namely the pairing of `self._get_yaml_config()` with `self.__init__()` to dynamically populate a common set of class attributes that can be referenced by the other methods in the dataset classes.

Also, this PR contains the code for #549 Merging it will also merge that PR

## Instructions to Review
TBD

### CODE REVIEW

**Comment by widal001** [comment]
@esfoobar-usds @switzersc-usds Here's the first slice of the code for the ETL checks. It looks like a lot of code, but only the last three commits are unique to this PR. The previous commits are from #549

**Comment by widal001** [comment]
Rebase to the last commit to main

**Comment by widal001** [comment]
Changes we discussed in today's office hours:

- TODO: Change `is_dataset` to `is_census` 
- TODO: Rename `geo_col` to `geoid_col`

**Comment by widal001** [comment]
@switzersc-usds @esfoobar-usds Hey all! Thanks for your patience on this PR, it's been a busy couple of weeks, but I think this should be even with main and ready for review

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Pull request merged**
