### PR TITLE
Implement downloads page and May 25th timed copy changes

### LINKED ISSUE #1240: Implement downloads page under Methodology and Data
# Purpose
Need to determine design for making all of the various files available to the public
Screen Shot 2022-04-04 at 4 31 15 PM

## Tasks
High Risk
- [x] add basic side nav
- [x] mobile layout to show nested options, while desktop show side nav

Low risk:
- [x] Indent Side Nav
- [x] get links on Download page with actual sizes
- [x] test a11y
- [x] remove tab on Personal Eng button
- [x] ensure both alerts will expire on May 25th
- [x] update 3rd bullet copy after May 25th
- [x] update RFI copy to after May25th
- [x] add unit tests

### PR DESCRIPTION
**Pull request by vim-usds**
# Purpose
- closes #1240 
- also ensure that some copy changes will occur on May 26th

# QA round 1

## QA spec: desktop
- [x] clicking on Methodology & Data should show a side nav with a `Meth & Data` option and `Downloads` option
- [x] clicking on Downloads should bring up the appropriate page
- [x] updated tag is removed from public eng. button

## QA spec: mobile
- [x] clicking on `Downloads` should bring to the appropriate page with no side nav

# QA round 2

## QA spec: desktop
- [ ] all 5 links should work (3 download and 2 open in new tab)
- [ ] all 5 links copy is correct
- [ ] all 5 links in Spanish
- [ ] all 5 links sizes are correct
- [ ] should work in safari (When using Safari, one may encounter a link opening rather than downloading. One can do a CTRL+click to get the menu to show up to allow which will allow one to download the file)

## QA spec: mobile
- [ ] The mobile navigation menu should be allowed to be opened/closed 
- [ ] The Methodology and Data menu should be open by default

## QA spec for May25th timed changes
- [ ] both alerts removed
- [ ] RFI message has appropriate message in English
- [ ] RFI box has appropriate message in Spanish
- [ ] 3rd bullet under map has appropriate message in English
- [ ] 3rd bullet under map has appropriate message in Spanish

### CODE REVIEW

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by vim-usds** [comment]
> 🍏

Thanks @esfoobar-usds !!!

**Comment by KameronKerger** [comment]
a couple of things @vim-usds 
* the csv and xlxs are flipped (link to the wrong version)
* on safari the csv doesn't download, it opens up the data in a new tab
* the size of the xlxs on my machine is 24.9 MB
* I don't love how in mobile view picking the first methodology and data does nothing - I think that is a pretty big usability issue. let's discuss
* should the pdf and tsd be "view" instead of download since they don't download? let me discuss with Beth and Katherine

**Comment by vim-usds** [comment]
When using Safari, one may encounter a link opening rather than downloading. One can do a CTRL+click to get the menu to show up to allow which will allow one to download the file:

Screen Shot 2022-05-25 at 6 10 24 PM

**Pull request merged**
