### PR TITLE
Remove inplace argument to prevent SettingWithCopyError

### PR DESCRIPTION
**Pull request by ahlusar1989**
This is related to Issue [898](https://github.com/usds/justice40-tool/issues/898).

I am using pandas-1.3.4.

This small change prevents the chained assignment that triggers the SettingWithCopyError exception.

### CODE REVIEW

**Comment by vim-usds** [comment]
@ahlusar1989 - This is just an FYI and no real action is needed here. I am new to the backend and I believe I got this error. I can't remember which command triggered that. 

I am re-running this now:

`poetry run python3 data_pipeline/application.py data-full-run -s aws`

Recently, this command did pass:

`poetry run python3 data_pipeline/application.py score-full-run`

**Comment by switzersc-usds** [comment]
Thanks for this fix @ahlusar1989 ! We're running the CI/CD checks now and will approve and merge once they've passed :)

**Comment by vim-usds** [comment]
Just ran the data-score-full and got the same error. This is good that we're on the same page!

**Comment by vim-usds** [comment]
@ahlusar1989, there are some checks failing.

One idea / theory that @switzersc-usds mentioned that it may mean that the linters need to be set up? I don't have these configured yet on my end. I believe it's some combination of black, flake and/or pylint?

I believe [this](https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/README.md#vscode) section of the README goes into it. I have to understand this myself at some point as well.

**Comment by switzersc-usds** [comment]
Exactly right! It looks like linting commands during the data checks are failing. I would recommend running `black` to format and then running `pylint` and `flake8` to identify any further styles that need to be updated. 

In terminal, from the `data/data-pipeline` directory, run:

```
poetry run black data_pipeline
poetry run pylint data_pipeline
poetry run flake8 data_pipeline
```

Then you can fix any errors that come up, commit, and push to update this PR.  Once the build is passing this will be all set!

Thanks!

**Comment by ahlusar1989** [comment]
Thanks, @switzersc-usds and @vim-usds

**Comment by ahlusar1989** [comment]
`reformatted data_pipeline/etl/score/etl_score_post.py
reformatted data_pipeline/etl/score/etl_score.py
All done! ✨ 🍰 ✨
2 files reformatted, 83 files left unchanged.
(justice-40-env) ➜  data-pipeline git:(ahlusar1989-patch-898) ✗ poetry run pylint data_pipeline

************* Module data_pipeline.etl.score.etl_score
data_pipeline/etl/score/etl_score.py:7:0: C0413: Import "from data_pipeline.etl.base import ExtractTransformLoad" should be placed at the top of the module (wrong-import-position)
data_pipeline/etl/score/etl_score.py:8:0: C0413: Import "from data_pipeline.score.score_runner import ScoreRunner" should be placed at the top of the module (wrong-import-position)
data_pipeline/etl/score/etl_score.py:9:0: C0413: Import "from data_pipeline.score import field_names" should be placed at the top of the module (wrong-import-position)
data_pipeline/etl/score/etl_score.py:10:0: C0413: Import "from data_pipeline.etl.score import constants" should be placed at the top of the module (wrong-import-position)
data_pipeline/etl/score/etl_score.py:12:0: C0413: Import "from data_pipeline.utils import get_module_logger" should be placed at the top of the module (wrong-import-position)
************* Module data_pipeline.etl.score.etl_score_post
data_pipeline/etl/score/etl_score_post.py:9:0: C0413: Import "from data_pipeline.etl.sources.census.etl_utils import check_census_data_source" should be placed at the top of the module (wrong-import-position)
data_pipeline/etl/score/etl_score_post.py:12:0: C0413: Import "from . import constants" should be placed at the top of the module (wrong-import-position)

-----------------------------------
Your code has been rated at 9.96/10

(justice-40-env) ➜  data-pipeline git:(ahlusar1989-patch-898) ✗ poetry run flake8 data_pipeline

data_pipeline/etl/score/etl_score.py:7:1: E402 module level import not at top of file
data_pipeline/etl/score/etl_score.py:8:1: E402 module level import not at top of file
data_pipeline/etl/score/etl_score.py:9:1: E402 module level import not at top of file
data_pipeline/etl/score/etl_score.py:10:1: E402 module level import not at top of file
data_pipeline/etl/score/etl_score.py:12:1: E402 module level import not at top of file
data_pipeline/etl/score/etl_score_post.py:9:1: E402 module level import not at top of file
data_pipeline/etl/score/etl_score_post.py:12:1: E402 module level import not at top of file
(justice-40-env) ➜  data-pipeline git:(ahlusar1989-patch-898) ✗ 
`

Perhaps these are the root cause. I will make the adjustments and see if this addresses the 1 failing check

**Comment by ahlusar1989** [comment]
@switzersc-usds @vim-usds Local tests from flake8 and pylint checks have been addressed.

**Review by lucasmbrown-usds — APPROVED** [review]
LGTM! 

I'm still curious why this was popping up for you but no one else.

**Pull request merged**
