### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by switzersc-usds**
Remove Gina Beena! <3

### CODE REVIEW

**Review by TomNUSDS — COMMENTED** [review]
Does not LGTM, but Approved anyways.

**Comment by switzersc-usds** [comment]
@TomNUSDS but you didnt approve!

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by TomNUSDS** [comment]
@switzersc-usds
> Does not LGTM, but Approved anyways.

d'oh. sorry.

**Pull request merged**
