### PR TITLE
Add address to search placeholder and add "at or above" to category copy for low income

### PR DESCRIPTION
**Pull request by vim-usds**
# Purpose
Add address to search placeholder and add "at or above" to category copy for low income

# QA

### QA spec
- [x] Search placeholder text reads "Search for an address, city state or ZIP" on desktop
- [x] "at or above" appears in low income copy under categories of meth. page
- [x] All copy changes are made to Spanish site as well

### QA spec
- [x] Search placeholder text reads "Search locations" on mobile
- [x] Update error message above SearchBar in English
- [x] Update error message above SearchBar in Spanish

### CODE REVIEW

**Comment by KameronKerger** [comment]
no go on mobile @vim-usds and can we get the search error message also updated with this fix
Screen Shot 2022-06-02 at 12 56 47 PM
Screenshot_20220602-125558
Screen Shot 2022-06-02 at 12 56 21 PM
?

**Comment by vim-usds** [comment]
@KameronKerger - thanks! Will get the error message in now. 

What is the name of the device you are using to test the mobile placeholder text? I'm trying to figure out the width on it and hoping it's over 480px (as this will be an easy fix then)

**Comment by KameronKerger** [comment]
I used the chrome browser and made it shrink and then I used my google pixel.

**Review by esfoobar-usds — APPROVED** [review]
🍏

**Comment by KameronKerger** [comment]
all good @vim-usds

**Pull request merged**
