### PR TITLE
Add RFI to contact page

### LINKED ISSUE #1442: Add RFI to contact page
Kameron to add mocks.

### PR DESCRIPTION
**Pull request by vim-usds**
# Purpose
Add RFI to contact page

## TIckets this PR closes
- closes #1442 

### QA link [here](http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/1515-f855f6/en/contact/)

- [x] is the RFI box aligned correctly?
- [x] does the RFI box render correctly on mobile?
- [x] is the heading copy correct?

QA round 2:
- [x] is the RFI box spaced correctly?
- [ ] is the body copy correct?
- [x] added v-spacing between contact page body and footer?

### CODE REVIEW

**Comment by KameronKerger** [comment]
1. can it be a little more narrow - maybe left align with the start of the 3rd column in the footer? 
Screen Shot 2022-03-30 at 3 23 40 PM
2. there is a typo (probably my bad) in the copy (remove the bolded first on):
During the beta period, comments may be submitted on the Climate and Economic Justice Screening Tool via CEQ’s 3. Request for Information **on** available on [federalregister.gov](https://www.federalregister.gov/d/2022-03920)
3. can we add some v-space buffer between the ending of the body area and the footer
 Screen Shot 2022-03-30 at 3 35 22 PM
4. mobile is looking good
Screenshot_20220330-153428

**Comment by vim-usds** [comment]
@KameronKerger

regarding comment 1. Sure!

We are using a 12 column layout (trying to use it everywhere but it's not completely integrated). We are currently distributing the 12 columns as  _7 columns for the first column_ and _5 for the second column_ (RFI box):



Screen Shot 2022-03-30 at 4 08 12 PM

Note: we can adjust the width of the gap, USWDS calls these [gutters](https://designsystem.digital.gov/utilities/layout-grid/)

The next way to split 12 columns would be 8 and 4:
Screen Shot 2022-03-30 at 4 07 28 PM

How does that look to you?

**Comment by KameronKerger** [comment]
I much prefer the 8 and 4 thank you @vim-usds

**Comment by KameronKerger** [comment]
just one more little thing @vim-usds - we need a period after federalregister.gov.

**Pull request merged**
