### PR TITLE
Add new custom colors basemap

### LINKED ISSUE #1682: Global export of all properties in basemap in MapBox (colors)
ALso is there a way to place the labels above. the census track. That would allow a less opaque tract style.

### PR DESCRIPTION
**Pull request by vim-usds**
# Purpose
- Attempt some new colors for the base map
- closes #1682 

## QA

QA spec [here](http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/1774-be0084/en/#3/33.47/-97.5)

- [x] Does the new map load on desktop?
- [x] Does the new map load on mobile?

BTW @KameronKerger, if you make any changes to the `j40-custom-colors` style (the one you've been working on) in MapBox and publish it, it should automatically update the QA link above! So in a way, you have an end-to-end system that will allow you to make changes to the basemap and see what it looks like all without any dev involvement!

Let me know if you have any questions!

### CODE REVIEW

**Comment by KameronKerger** [comment]
it loads on both platforms but we have some additional work to do. a couple of examples / screenshots attached
Screen Shot 2022-08-02 at 1 44 43 PM
Screen Shot 2022-08-02 at 1 44 39 PM
Screen Shot 2022-08-02 at 1 44 01 PM
Screen Shot 2022-08-02 at 1 43 06 PM
.

**Comment by vim-usds** [comment]
@KameronKerger - I'm seeing this above showing that we have areas on the map that are pretty similar to the census tract color? Not bad if that's all we have left! Great job getting these colors figured out. I know how monumental of a task this is. 

Let me know if I can support. Also Mikel is on the open source chat and pretty responsive in case that resource is needed.

**Comment by KameronKerger** [comment]
OK I fixed it in the custom map also
Screen Shot 2022-08-23 at 11 15 50 AM

**Comment by vim-usds** [comment]
@KameronKerger - great thank you!

**Pull request closed without merging**
